### ISSUE TITLE
Release up to Tomcat 9.0.80?

### ISSUE THREAD

**Issue by cidus** [tomcat-slf4j-logback/tomcat9-slf4j-logback#75]
Any updates on this? Thanks

**Comment by hazendaz** [comment]
You can use any copy really for any tomcat.  The code of tomcats isn't used.  Its completely replaced so the version doesn't actually matter in that sense.  The releases are otherwise slow at the moment as logstash has been added after many years of users asking for it and that part is still to be tested.
